[[headers]]
for = "/*"
  [headers.values]
  Content-Security-Policy = "frame-ancestors 'self' https://builder.io"

[build]
  publish = "public"
  command = "gatsby build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200